const ACCESS_ROLES = Object.freeze({
  EVENT_CREATOR: "EVENT_CREATOR",
  EVENT_ADMIN: "EVENT_ADMIN",
  ACTIVITY_ADMIN: "ACTIVITY_ADMIN",
  PARTICIPANT: "PARTICIPANT",
});

const TODO_STATUS = Object.freeze({
  READY_FOR_WORK: "READY_FOR_WORK",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE",
});

module.exports = {
  ACCESS_ROLES,
  TODO_STATUS
};
